# Shadowrocket config (GitHub managed)

[General]
bypass-system = true
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local
ipv6 = false

# 👉 ссылка на правила (ВАЖНО: без refs/heads)
rule-set = https://raw.githubusercontent.com/vanzzzzzzz/vpn-config/main/rules.list

[Rule]
# Подгружаем правила с GitHub
RULE-SET,rules.list,DIRECT

# Всё остальное через VPN
FINAL,PROXY
