[General]
bypass-system = true
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local
ipv6 = false

[Rule]
DOMAIN-SUFFIX,mos.ru,DIRECT
DOMAIN-SUFFIX,gosuslugi.ru,DIRECT
DOMAIN-SUFFIX,nalog.gov.ru,DIRECT
DOMAIN-SUFFIX,sberbank.ru,DIRECT
DOMAIN-SUFFIX,sber.ru,DIRECT
DOMAIN-SUFFIX,online.sberbank.ru,DIRECT
DOMAIN-SUFFIX,alfabank.ru,DIRECT

DOMAIN-SUFFIX,tdm.mos.ru,DIRECT
DOMAIN-SUFFIX,karavaevi.ru,DIRECT
DOMAIN-SUFFIX,avito.ru,DIRECT

DOMAIN-SUFFIX,ru,DIRECT
DOMAIN-SUFFIX,рф,DIRECT

IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
IP-CIDR,172.16.0.0/12,DIRECT,no-resolve

FINAL,PROXY
